### ISSUE TITLE
Reconcile - component k8s service type can't be overridden in the env specific config file.

### ISSUE THREAD

**Issue by marcinc** [appvia/kev#288]
It looks like it's impossible to override the K8s service type for compose services auto-inferred as LoadBalancer.

To replicate get an example compose service spec, e.g.:

```yaml
version: '3'
services:
  mongo:
    image: mongo:3.2
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017

volumes:
  mongo-data:
```  

then override k8s service type in env specific override, e.g.:

```yaml
version: "3"
services:
  mongo:
    labels:
      kev.service.type: clusterip
```

Reconciler will persist the `kev.service.type` label, however its value will revert to that originally inferred from the source compose i.e. LoadBalancer.

**Comment by ezodude** [comment]
As discussed before, this is by design since we view the `kev.service.type` as specialised configuration better handled internally by `Kev`.

**I propose re-working this as a new feature rather than a bug.**

Here's a proposal that can allow more informed developers to force an override,
- Introduce a new `reconcile-exclude` param in `kev.yaml`.
- `reconcile-exclude`, enables a developer to exclude specific service labels from reconciliation - as they know best.
- For now, it will only affect `kev.service.type` (its the only label that is affected by the base changes).
- If the service is removed, reconciliation will also remove the `reconcile-exclude.<service>` from `kev.yaml`.

Here's a draft of how this would look:
```yaml
compose:
  - docker-compose.yaml
environments:
  dev:
    source: docker-compose.kev.dev.yaml
    reconcile-exclude:
      db:
      - "kev.service.type"
  staging:
    source: docker-compose.kev.staging.yaml
```
