### ISSUE TITLE
Exclude from reconcile

### ISSUE THREAD

**Issue by ezodude** [appvia/kev#299]
As a developer, I want reconciliation to keep my environment's overridden K8s service type ignoring the inferred value.

So, I can customise my app's deployment beyond Kev conventions.

(This addresses https://github.com/appvia/kev/issues/288)

As a bonus, 

- The solution should be generic enough to accommodate different settings.
- Surface `kev.service.type` label in the condensed env override docker-compose.yaml.

## Typical Workflow

- First init, generates all yaml env overrides.
- Update to the ports field - reconciled.
- Edit kev.yaml to exclude an environment's `<service>.labels.<label>` config.
- Update to the ports field
    - Ignore yaml env override service.type.
    - Update other yaml env override service.type.

## Solution

- Introduce a new `reconcile-exclude` param in `kev.yaml`.
- `reconcile-exclude`, enables a developer to exclude specific service labels from reconciliation - as they know best.
- For now, it will only affect `kev.service.type` (its the only label that is affected by the base changes).
- If the service is removed, reconciliation will also remove the `reconcile-exclude.<service>` from `kev.yaml`.

Here's a draft of how this would look:
```yaml
compose:
  - docker-compose.yaml
environments:
  dev:
    source: docker-compose.kev.dev.yaml
    reconcile-exclude:
      db:
      - "kev.service.type"
  staging:
    source: docker-compose.kev.staging.yaml
```

**Comment by ezodude** [comment]
Reworking the draft solution.

I am going for something easily explainable and extendable, esp. if we ever need to accommodate `volumes` in the future.

Also, I am no longer using the word `source` so as not to confuse with the project's `docker-compose` sources.

```yaml
compose:
  - docker-compose.yaml
environments:
  dev:
    envfile: docker-compose.kev.dev.yaml
    detach:
      - type: service
        name: db
        labels:
          - kev.service.type
  staging:
    envfile: docker-compose.kev.staging.yaml
```
