### ISSUE TITLE
Support dependent env variables

### ISSUE THREAD

**Issue by marcinc** [appvia/kev#391]
Compose Environment variables which values are dependent on other environment variables must be ordered properly so that they can be expanded correctly. Should allow for env variables with templated values that reference other environment variables, e.g.

```yaml
# docker-compose.yaml

environment:
  MY_VAR: {{FOO}}/{{BAR}}
  FOO: foo
  BAR: bar
```

Should translate to the following in k8s manifest:

```
    spec:
      containers:
        - env:
            - name: FOO
              value: "foo"
            - name: BAR
              value: "bar"
            - name: MY_VAR
              value: "$(FOO)/$(BAR)"
```
