### ISSUE TITLE
Migrate configuration from labels to x-k8s extension

### ISSUE THREAD

**Issue by marcinc** [appvia/kev#434]
This issue describes the configuration migration plan from labels (used currently) to extensions.

The following represents an example structure for Kubernetes specific configuration:

```yaml
services:
    x-k8s:
        enabled: true
        workload:
            replicas: 1
            type: Deployment
            service-account-name: saname
            restart-policy: Always
            rolling-update-max-surge: 1
            annotations: # this is a new concept which we currently don't support
              key1: val1
              key2: val2
            image-pull:
                policy: IfNotPresent
                secret: mypullsecret
            pod-security:
                run-as-user: 1000
                run-as-group: 1000
                run-as-group: 2000
                fs-group: 1000
            autoscale:
                max-replicas: 10
                cpu-threshold: 70
                mem-threshold: 70
            resource:
                cpu: 0.1
                max-cpu: 1
                memory: 10Mi
                max-memory: 500Mi
            liveness-probe:
                exec:
                   command: "your command"
                interval:
                retries: 4
                initial-delay: 1m
                timeout: 10s
            readiness-probe:
                http:
                  port: 8080
                  path: /
                interval:
                retries: 4
                initial-delay: 1m
                timeout: 10s
        service:
            type: ClusterIP
            nodeport:
            expose:
                domain: domain.com
                tls-secret: my-domain-tls
                ingress-annotations:
                    kubernetes.io/ingress.class: external
                    cert-manager.io/cluster-issuer: prod-le-dns01
                    ...
```

# For Volumes

```yaml
volumes:
    x-k8s:
        storage-class: ssd
        size: 10Gi
        selector: my-volume-selector-label
```

Only keys that should be overridden / set should be provided and visible... All the rest hidden by default!
