### ISSUE TITLE
Introduce pod annotation configuration

### ISSUE THREAD

**Issue by ezodude** [appvia/kev#562]
```yaml
services:
    x-k8s:
        disabled: false
        workload:
            ...
            annotations: # pod annotations - this is a new concept which we currently don't support
              key1: val1
              key2: val2
```
